# This is a basic workflow to help you get started with Actions

name: Prepare / Build / Deploy / Clean

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    name: Install & Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '15.14'

      - name: Cache current work folder
        uses: actions/cache@v2
        env:
          cache-name: cache-repo
        with:
          path: ./*
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.sha }}

      - name: Install deps
        run: yarn

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test

  # This workflow contains a single job called "build"
  build:
    name: Build the repo for deply
    needs: [prepare]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '15.14'

      - name: Cache current work folder
        uses: actions/cache@v2
        env:
          cache-name: cache-repo
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./*
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.sha }}

      - name: Cache current build folder
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.sha }}-build

      - name: Building
        run: yarn run build

  deploy:
    name: Deploy to amazon S3
    needs: [build]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache current build folder
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ github.sha }}-build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
          SOURCE_DIR: './build/'      # optional: defaults to entire repository

  clean:
    name: Clean CDN caches via Cloudfront
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo TODO clean job